import type {
  Atendimento,
  DashboardData,
  FilaEsperaItem,
  HistoricoAtendimento,
  MotoristaFrota,
  PerfilAtendente,
  TicketRecebido,
  TicketResumo,
  Usuario,
} from '@/types';

// ============================================================
// Dados mock — apresentação FBLog Atende
// (substituíveis por chamadas reais quando VITE_USE_MOCK=false)
// ============================================================

export const USUARIO_DEMO: Usuario = {
  id: 'u-1',
  nome: 'Mariana Costa',
  email: 'mariana.costa@fblog.com.br',
  cor: 'violet',
  funcao: 'atendente',
};

export const TICKET_RECEBIDO: TicketRecebido = {
  id: 't-novo',
  nome: 'Sérgio Tavares',
  canal: 'whatsapp',
  cor: 'teal',
};

export const FILA_ATENDIMENTOS: TicketResumo[] = [
  {
    id: 'a-04812',
    protocolo: '#FB-2026-04812',
    motoristaNome: 'Rafael Monteiro',
    assunto: 'Frete recusado — divergência no valor da carga',
    canal: 'whatsapp',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    tempo: '2 min',
    sessaoRestante: '18h42',
    sessaoStatus: 'ok',
    prioridade: 'warn',
    responsavel: 'you',
    cor: 'teal',
    ativo: true,
  },
  {
    id: 'a-04809',
    protocolo: '#FB-2026-04809',
    motoristaNome: 'Beatriz Almeida',
    assunto: 'Atualização de documentos — CNH vencendo',
    canal: 'whatsapp',
    veiculo: 'Scania R450',
    placa: 'BTA-9J04',
    tempo: '8 min',
    sessaoRestante: '22h10',
    sessaoStatus: 'ok',
    prioridade: 'ok',
    responsavel: 'ia',
    cor: 'rose',
  },
  {
    id: 'a-04790',
    protocolo: '#FB-2026-04790',
    motoristaNome: 'Lucas Ferreira',
    assunto: 'Carga não localizada no app de rastreio',
    canal: 'telefone',
    veiculo: 'Mercedes Actros',
    placa: 'LCF-7C55',
    tempo: '13 min',
    sessaoRestante: '02h18',
    sessaoStatus: 'bad',
    prioridade: 'bad',
    responsavel: 'you',
    cor: 'amber',
  },
  {
    id: 'a-04751',
    protocolo: '#FB-2026-04751',
    motoristaNome: 'Patrícia Gomes',
    assunto: 'Dúvida sobre pagamento do frete de Goiânia',
    canal: 'chat',
    veiculo: 'DAF XF',
    placa: 'PTG-1A77',
    tempo: '21 min',
    sessaoRestante: '16h02',
    sessaoStatus: 'ok',
    prioridade: 'ok',
    responsavel: 'ia',
    cor: 'violet',
  },
  {
    id: 'a-04738',
    protocolo: '#FB-2026-04738',
    motoristaNome: 'Eduardo Ramos',
    assunto: 'Cadastro de ANTT desatualizado',
    canal: 'whatsapp',
    veiculo: 'Iveco Hi-Way',
    placa: 'EDR-4K23',
    tempo: '34 min',
    sessaoRestante: '09h55',
    sessaoStatus: 'warn',
    prioridade: 'warn',
    responsavel: 'ia',
    cor: 'green',
  },
];

export const ATENDIMENTO_ATIVO: Atendimento = {
  id: 'a-04812',
  protocolo: '#FB-2026-04812',
  assunto: 'Divergência no valor da carga',
  categoria: 'Frete / Pagamento',
  canal: 'whatsapp',
  responsavel: 'you',
  sessaoRestante: '18h42',
  sessaoStatus: 'ok',
  prioridade: 'warn',
  motorista: {
    id: 'm-1',
    nome: 'Rafael Monteiro',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    cnh: '0428 7715 901',
    categoria: 'E',
    antt: '12345678',
    validadeCnh: '08/2027',
    cadastrado: true,
    cor: 'teal',
  },
  mensagens: [
    {
      id: 'm1',
      autor: 'in',
      hora: '08:02',
      texto:
        'Bom dia! Recebi um frete de Uberlândia → Campinas mas o valor que apareceu pra mim tá diferente do combinado.',
    },
    {
      id: 'm2',
      autor: 'ia',
      hora: '08:02',
      texto:
        'Olá, Rafael! Sou a assistente virtual da FBLog. Já abri o protocolo #FB-2026-04812 e localizei seu cadastro. Pode me confirmar a placa do veículo para eu verificar o frete?',
    },
    {
      id: 'm3',
      autor: 'in',
      hora: '08:04',
      texto: 'É a RKL-2F18, Volvo FH. O frete tava como R$ 4.200 e apareceu R$ 3.800.',
    },
    {
      id: 'm4',
      autor: 'take',
      texto: 'Mariana assumiu o atendimento da IA · 08:05',
    },
    {
      id: 'm5',
      autor: 'out',
      hora: '08:06',
      texto:
        'Oi Rafael, aqui é a Mariana, assumi seu atendimento. Houve um ajuste de pedágio no trecho, mas o valor da carga continua R$ 4.200. Vou corrigir a exibição e te envio o comprovante agora.',
    },
    {
      id: 'm6',
      autor: 'in',
      hora: '08:07',
      texto: 'Beleza! Já mando a foto do CRLV também pra atualizar o cadastro.',
    },
  ],
  documentos: [
    { id: 'd1', nome: 'CNH — frente e verso', meta: 'JPG · enviado 08:05', tipo: 'cnh' },
    { id: 'd2', nome: 'CRLV 2026', meta: 'PDF · enviado 08:07', tipo: 'crlv' },
  ],
  historico: [
    { titulo: 'Frete SP → MG · pagamento', sub: '#FB-04790 · 18/06 · Encerrado', encerrado: true },
    { titulo: 'Atualização de ANTT', sub: '#FB-04612 · 02/06 · Encerrado', encerrado: true },
  ],
};

export const DASHBOARD: DashboardData = {
  kpis: [
    { k: 'Atendimentos hoje', v: '24', d: '+6 vs. ontem', up: true, ic: 'inbox', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Sessões abertas', v: '5', d: '2 < 6h restantes', up: false, ic: 'clock', cor: 'var(--warn)', fundo: 'var(--warn-sf)' },
    { k: 'Tempo médio de resposta', v: '1m48', d: '-22s vs. meta', up: true, ic: 'bolt', cor: 'var(--ok)', fundo: 'var(--ok-sf)' },
    { k: 'Conversão de fretes', v: '62%', d: '+5 p.p. no mês', up: true, ic: 'route', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Resolvidos pela IA', v: '9', d: 'sem intervenção', up: true, ic: 'ai', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Encerrados hoje', v: '17', d: '+3 vs. ontem', up: true, ic: 'check', cor: 'var(--ok)', fundo: 'var(--ok-sf)' },
  ],
  historico: [
    { protocolo: '#FB-04812', nome: 'Rafael Monteiro', cor: 'teal', assunto: 'Divergência no valor da carga', placa: 'RKL-2F18', duracao: 'ativo', duracaoCor: 'var(--ok)', conversao: 'Em frete', conversaoStatus: 'blue' },
    { protocolo: '#FB-04809', nome: 'Beatriz Almeida', cor: 'rose', assunto: 'Atualização de CNH', placa: 'BTA-9J04', duracao: '12m04', duracaoCor: 'var(--ink-2)', conversao: '—', conversaoStatus: 'mut' },
    { protocolo: '#FB-04790', nome: 'Lucas Ferreira', cor: 'amber', assunto: 'Carga não localizada', placa: 'LCF-7C55', duracao: '31m18', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
    { protocolo: '#FB-04772', nome: 'Patrícia Gomes', cor: 'violet', assunto: 'Pagamento frete Goiânia', placa: 'PTG-1A77', duracao: '08m42', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
    { protocolo: '#FB-04751', nome: 'Eduardo Ramos', cor: 'green', assunto: 'Cadastro de ANTT', placa: 'EDR-4K23', duracao: '05m10', duracaoCor: 'var(--ink-2)', conversao: 'Sem frete', conversaoStatus: 'bad' },
    { protocolo: '#FB-04738', nome: 'Antônio Brito', cor: 'slate', assunto: 'Dúvida sobre rota e pedágio', placa: 'ANB-3T90', duracao: '14m55', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  ],
  recebidos: [
    { id: 'r1', nome: 'Sérgio Tavares', cor: 'teal', canal: 'whatsapp', tempo: 'agora', assunto: 'Frete de retorno disponível?', placa: 'SGT-6P21', novo: true },
    { id: 'r2', nome: 'Marina Lopes', cor: 'violet', canal: 'chat', tempo: '1 min', assunto: 'Comprovante de entrega', placa: 'MNL-8R44', novo: true },
  ],
  proximos: [
    { nome: 'Helena Dias', cor: 'amber', canal: 'chat', tempo: '5 min' },
    { nome: 'Antônio Brito', cor: 'slate', canal: 'telefone', tempo: '9 min' },
    { nome: 'Carlos Eduardo', cor: 'green', canal: 'whatsapp', tempo: '12 min' },
  ],
};

// ---- Fila de espera -------------------------------------------------------

export const FILA_ESPERA: FilaEsperaItem[] = [
  {
    id: 'f-1',
    posicao: 1,
    nome: 'Sérgio Tavares',
    cor: 'teal',
    canal: 'whatsapp',
    placa: 'SGT-6P21',
    veiculo: 'Volvo FH 460',
    assunto: 'Frete de retorno disponível?',
    espera: 'agora',
    prioridade: 'warn',
    responsavel: 'ia',
  },
  {
    id: 'f-2',
    posicao: 2,
    nome: 'Marina Lopes',
    cor: 'violet',
    canal: 'chat',
    placa: 'MNL-8R44',
    veiculo: 'Scania R450',
    assunto: 'Comprovante de entrega não chegou',
    espera: '1 min',
    prioridade: 'ok',
    responsavel: 'ia',
  },
  {
    id: 'f-3',
    posicao: 3,
    nome: 'Helena Dias',
    cor: 'amber',
    canal: 'chat',
    placa: 'HLD-2K90',
    veiculo: 'Mercedes Actros',
    assunto: 'Reagendamento de coleta em Campinas',
    espera: '5 min',
    prioridade: 'ok',
    responsavel: 'ia',
  },
  {
    id: 'f-4',
    posicao: 4,
    nome: 'Antônio Brito',
    cor: 'slate',
    canal: 'telefone',
    placa: 'ANB-3T90',
    veiculo: 'DAF XF',
    assunto: 'Dúvida sobre rota e pedágio',
    espera: '9 min',
    prioridade: 'bad',
    responsavel: 'ia',
  },
  {
    id: 'f-5',
    posicao: 5,
    nome: 'Carlos Eduardo',
    cor: 'green',
    canal: 'whatsapp',
    placa: 'CED-7F12',
    veiculo: 'Iveco S-Way',
    assunto: 'Atualização de dados bancários',
    espera: '12 min',
    prioridade: 'warn',
    responsavel: 'ia',
  },
  {
    id: 'f-6',
    posicao: 6,
    nome: 'Roberto Nunes',
    cor: 'blue',
    canal: 'whatsapp',
    placa: 'RBN-1A55',
    veiculo: 'Volvo FH 540',
    assunto: 'Carga com avaria — abrir ocorrência',
    espera: '17 min',
    prioridade: 'bad',
    responsavel: 'ia',
  },
];

// ---- Frota de motoristas --------------------------------------------------

export const MOTORISTAS_FROTA: MotoristaFrota[] = [
  {
    id: 'm-1',
    nome: 'Rafael Monteiro',
    cor: 'teal',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(34) 99812-4471',
    localizacao: 'Uberlândia, MG',
    ultimaAtividade: 'há 3 min',
    cadastroCompleto: true,
    fretesMes: 11,
    frete: { origem: 'Uberlândia, MG', destino: 'Campinas, SP', progresso: 62, eta: 'hoje 18h40' },
  },
  {
    id: 'm-2',
    nome: 'Beatriz Almeida',
    cor: 'rose',
    veiculo: 'Scania R450',
    placa: 'BTA-9J04',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(11) 99145-2093',
    localizacao: 'Ribeirão Preto, SP',
    ultimaAtividade: 'há 12 min',
    cadastroCompleto: false,
    fretesMes: 8,
  },
  {
    id: 'm-3',
    nome: 'Lucas Ferreira',
    cor: 'amber',
    veiculo: 'Mercedes Actros',
    placa: 'LCF-7C55',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(62) 99633-7788',
    localizacao: 'Anápolis, GO',
    ultimaAtividade: 'há 1 min',
    cadastroCompleto: true,
    fretesMes: 14,
    frete: { origem: 'Goiânia, GO', destino: 'Brasília, DF', progresso: 88, eta: 'hoje 15h10' },
  },
  {
    id: 'm-4',
    nome: 'Patrícia Gomes',
    cor: 'violet',
    veiculo: 'DAF XF',
    placa: 'PTG-1A77',
    categoria: 'D',
    status: 'disponivel',
    telefone: '(62) 99870-1122',
    localizacao: 'Goiânia, GO',
    ultimaAtividade: 'há 8 min',
    cadastroCompleto: true,
    fretesMes: 6,
  },
  {
    id: 'm-5',
    nome: 'Eduardo Ramos',
    cor: 'green',
    veiculo: 'Iveco Hi-Way',
    placa: 'EDR-4K23',
    categoria: 'E',
    status: 'descanso',
    telefone: '(41) 99205-6540',
    localizacao: 'Curitiba, PR',
    ultimaAtividade: 'há 40 min',
    cadastroCompleto: false,
    fretesMes: 9,
  },
  {
    id: 'm-6',
    nome: 'Antônio Brito',
    cor: 'slate',
    veiculo: 'DAF XF',
    placa: 'ANB-3T90',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(31) 99411-8890',
    localizacao: 'Betim, MG',
    ultimaAtividade: 'há 6 min',
    cadastroCompleto: true,
    fretesMes: 12,
    frete: { origem: 'Belo Horizonte, MG', destino: 'Vitória, ES', progresso: 34, eta: 'amanhã 09h20' },
  },
  {
    id: 'm-7',
    nome: 'Carlos Eduardo',
    cor: 'green',
    veiculo: 'Iveco S-Way',
    placa: 'CED-7F12',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(19) 99788-3301',
    localizacao: 'Campinas, SP',
    ultimaAtividade: 'há 15 min',
    cadastroCompleto: true,
    fretesMes: 7,
  },
  {
    id: 'm-8',
    nome: 'Helena Dias',
    cor: 'amber',
    veiculo: 'Mercedes Actros',
    placa: 'HLD-2K90',
    categoria: 'D',
    status: 'manutencao',
    telefone: '(11) 99566-4432',
    localizacao: 'Jundiaí, SP',
    ultimaAtividade: 'há 2 h',
    cadastroCompleto: true,
    fretesMes: 5,
  },
  {
    id: 'm-9',
    nome: 'Roberto Nunes',
    cor: 'blue',
    veiculo: 'Volvo FH 540',
    placa: 'RBN-1A55',
    categoria: 'E',
    status: 'offline',
    telefone: '(47) 99320-7765',
    localizacao: 'Joinville, SC',
    ultimaAtividade: 'ontem 19h05',
    cadastroCompleto: false,
    fretesMes: 3,
  },
  {
    id: 'm-10',
    nome: 'Sérgio Tavares',
    cor: 'teal',
    veiculo: 'Volvo FH 460',
    placa: 'SGT-6P21',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(51) 99188-2244',
    localizacao: 'Porto Alegre, RS',
    ultimaAtividade: 'agora',
    cadastroCompleto: true,
    fretesMes: 10,
  },
  {
    id: 'm-11',
    nome: 'Marina Lopes',
    cor: 'violet',
    veiculo: 'Scania R450',
    placa: 'MNL-8R44',
    categoria: 'D',
    status: 'em_carga',
    telefone: '(21) 99744-9012',
    localizacao: 'Duque de Caxias, RJ',
    ultimaAtividade: 'há 4 min',
    cadastroCompleto: true,
    fretesMes: 13,
    frete: { origem: 'Rio de Janeiro, RJ', destino: 'Juiz de Fora, MG', progresso: 51, eta: 'hoje 20h00' },
  },
  {
    id: 'm-12',
    nome: 'Fernando Dias',
    cor: 'rose',
    veiculo: 'Iveco Hi-Way',
    placa: 'FND-5G30',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(85) 99622-1187',
    localizacao: 'Fortaleza, CE',
    ultimaAtividade: 'há 20 min',
    cadastroCompleto: true,
    fretesMes: 4,
  },
];

// ---- Histórico de atendimentos -------------------------------------------

export const HISTORICO_ATENDIMENTOS: HistoricoAtendimento[] = [
  { id: 'h-1', protocolo: '#FB-04812', motoristaNome: 'Rafael Monteiro', cor: 'teal', placa: 'RKL-2F18', assunto: 'Divergência no valor da carga', canal: 'whatsapp', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-02', dataLabel: '02 jul 2026, 08:12', duracao: '22m10', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-2', protocolo: '#FB-04809', motoristaNome: 'Beatriz Almeida', cor: 'rose', placa: 'BTA-9J04', assunto: 'Atualização de CNH', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-07-02', dataLabel: '02 jul 2026, 07:48', duracao: '12m04', conversao: '—', conversaoStatus: 'mut' },
  { id: 'h-3', protocolo: '#FB-04790', motoristaNome: 'Lucas Ferreira', cor: 'amber', placa: 'LCF-7C55', assunto: 'Carga não localizada', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-01', dataLabel: '01 jul 2026, 16:31', duracao: '31m18', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-4', protocolo: '#FB-04772', motoristaNome: 'Patrícia Gomes', cor: 'violet', placa: 'PTG-1A77', assunto: 'Pagamento frete Goiânia', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-01', dataLabel: '01 jul 2026, 14:02', duracao: '08m42', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-5', protocolo: '#FB-04751', motoristaNome: 'Eduardo Ramos', cor: 'green', placa: 'EDR-4K23', assunto: 'Cadastro de ANTT', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-30', dataLabel: '30 jun 2026, 11:20', duracao: '05m10', conversao: 'Sem frete', conversaoStatus: 'bad' },
  { id: 'h-6', protocolo: '#FB-04738', motoristaNome: 'Antônio Brito', cor: 'slate', placa: 'ANB-3T90', assunto: 'Dúvida sobre rota e pedágio', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-30', dataLabel: '30 jun 2026, 09:55', duracao: '14m55', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-7', protocolo: '#FB-04701', motoristaNome: 'Carlos Eduardo', cor: 'green', placa: 'CED-7F12', assunto: 'Atualização de dados bancários', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-27', dataLabel: '27 jun 2026, 15:40', duracao: '06m30', conversao: 'Em frete', conversaoStatus: 'blue' },
  { id: 'h-8', protocolo: '#FB-04688', motoristaNome: 'Helena Dias', cor: 'amber', placa: 'HLD-2K90', assunto: 'Reagendamento de coleta', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-25', dataLabel: '25 jun 2026, 10:12', duracao: '18m47', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-9', protocolo: '#FB-04655', motoristaNome: 'Roberto Nunes', cor: 'blue', placa: 'RBN-1A55', assunto: 'Carga com avaria — ocorrência', canal: 'whatsapp', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-22', dataLabel: '22 jun 2026, 17:05', duracao: '41m02', conversao: '—', conversaoStatus: 'mut' },
  { id: 'h-10', protocolo: '#FB-04612', motoristaNome: 'Sérgio Tavares', cor: 'teal', placa: 'SGT-6P21', assunto: 'Frete de retorno', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-18', dataLabel: '18 jun 2026, 08:30', duracao: '09m15', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-11', protocolo: '#FB-04588', motoristaNome: 'Marina Lopes', cor: 'violet', placa: 'MNL-8R44', assunto: 'Comprovante de entrega', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-12', dataLabel: '12 jun 2026, 13:22', duracao: '11m48', conversao: 'Em frete', conversaoStatus: 'blue' },
  { id: 'h-12', protocolo: '#FB-04503', motoristaNome: 'Fernando Dias', cor: 'rose', placa: 'FND-5G30', assunto: 'Dúvida sobre nota fiscal', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-05-28', dataLabel: '28 mai 2026, 09:10', duracao: '16m33', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-13', protocolo: '#FB-04471', motoristaNome: 'Beatriz Almeida', cor: 'rose', placa: 'BTA-9J04', assunto: 'Cadastro de veículo', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-05-20', dataLabel: '20 mai 2026, 10:44', duracao: '07m19', conversao: 'Sem frete', conversaoStatus: 'bad' },
  { id: 'h-14', protocolo: '#FB-04409', motoristaNome: 'Lucas Ferreira', cor: 'amber', placa: 'LCF-7C55', assunto: 'Pagamento pendente', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-05-11', dataLabel: '11 mai 2026, 15:58', duracao: '24m01', conversao: 'Frete fechado', conversaoStatus: 'ok' },
];

// ---- Perfil do atendente --------------------------------------------------

export const PERFIL_ATENDENTE: PerfilAtendente = {
  id: 'u-1',
  nome: 'Mariana Costa',
  email: 'mariana.costa@fblog.com.br',
  telefone: '(11) 99820-3345',
  cor: 'violet',
  funcao: 'atendente',
  metaDiaria: 30,
  disponivel: true,
};
