import type {
  Atendimento,
  DashboardData,
  FilaEsperaItem,
  HistoricoAtendimento,
  MotoristaFrota,
  PerfilAtendente,
  TicketRecebido,
  TicketResumo,
  Usuario,
} from '@/types';

// ============================================================
// Dados mock — apresentação FBLog Atende
// (substituíveis por chamadas reais quando VITE_USE_MOCK=false)
// ============================================================

/** Hora atual no formato HH:MM (para mensagens recém-chegadas). */
function agoraCurto(): string {
  const d = new Date();
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
}

export const USUARIO_DEMO: Usuario = {
  id: 'u-1',
  nome: 'Mariana Costa',
  email: 'mariana.costa@fblog.com.br',
  cor: 'violet',
  funcao: 'atendente',
};

export const TICKET_RECEBIDO: TicketRecebido = {
  id: 't-novo',
  nome: 'Sérgio Tavares',
  canal: 'whatsapp',
  cor: 'teal',
};

export const FILA_ATENDIMENTOS: TicketResumo[] = [
  {
    id: 'a-04812',
    protocolo: '#FB-2026-04812',
    motoristaNome: 'Rafael Monteiro',
    assunto: 'Frete recusado — divergência no valor da carga',
    canal: 'whatsapp',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    tempo: '2 min',
    sessaoRestante: '18h42',
    sessaoStatus: 'ok',
    prioridade: 'warn',
    responsavel: 'you',
    cor: 'teal',
    ativo: true,
  },
  {
    id: 'a-04809',
    protocolo: '#FB-2026-04809',
    motoristaNome: 'Beatriz Almeida',
    assunto: 'Atualização de documentos — CNH vencendo',
    canal: 'whatsapp',
    veiculo: 'Scania R450',
    placa: 'BTA-9J04',
    tempo: '8 min',
    sessaoRestante: '22h10',
    sessaoStatus: 'ok',
    prioridade: 'ok',
    responsavel: 'ia',
    cor: 'rose',
  },
  {
    id: 'a-04790',
    protocolo: '#FB-2026-04790',
    motoristaNome: 'Lucas Ferreira',
    assunto: 'Carga não localizada no app de rastreio',
    canal: 'telefone',
    veiculo: 'Mercedes Actros',
    placa: 'LCF-7C55',
    tempo: '13 min',
    sessaoRestante: '02h18',
    sessaoStatus: 'bad',
    prioridade: 'bad',
    responsavel: 'you',
    cor: 'amber',
  },
  {
    id: 'a-04751',
    protocolo: '#FB-2026-04751',
    motoristaNome: 'Patrícia Gomes',
    assunto: 'Dúvida sobre pagamento do frete de Goiânia',
    canal: 'chat',
    veiculo: 'DAF XF',
    placa: 'PTG-1A77',
    tempo: '21 min',
    sessaoRestante: '16h02',
    sessaoStatus: 'ok',
    prioridade: 'ok',
    responsavel: 'ia',
    cor: 'violet',
  },
  {
    id: 'a-04738',
    protocolo: '#FB-2026-04738',
    motoristaNome: 'Eduardo Ramos',
    assunto: 'Cadastro de ANTT desatualizado',
    canal: 'whatsapp',
    veiculo: 'Iveco Hi-Way',
    placa: 'EDR-4K23',
    tempo: '34 min',
    sessaoRestante: '09h55',
    sessaoStatus: 'warn',
    prioridade: 'warn',
    responsavel: 'ia',
    cor: 'green',
  },
];

export const ATENDIMENTO_ATIVO: Atendimento = {
  id: 'a-04812',
  protocolo: '#FB-2026-04812',
  assunto: 'Divergência no valor da carga',
  categoria: 'Frete / Pagamento',
  canal: 'whatsapp',
  responsavel: 'you',
  sessaoRestante: '18h42',
  sessaoStatus: 'ok',
  prioridade: 'warn',
  motorista: {
    id: 'm-1',
    nome: 'Rafael Monteiro',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    cnh: '0428 7715 901',
    categoria: 'E',
    antt: '12345678',
    validadeCnh: '08/2027',
    cadastrado: true,
    cor: 'teal',
  },
  mensagens: [
    {
      id: 'm1',
      autor: 'in',
      hora: '08:02',
      texto:
        'Bom dia! Recebi um frete de Uberlândia → Campinas mas o valor que apareceu pra mim tá diferente do combinado.',
    },
    {
      id: 'm2',
      autor: 'ia',
      hora: '08:02',
      texto:
        'Olá, Rafael! Sou a assistente virtual da FBLog. Já abri o protocolo #FB-2026-04812 e localizei seu cadastro. Pode me confirmar a placa do veículo para eu verificar o frete?',
    },
    {
      id: 'm3',
      autor: 'in',
      hora: '08:04',
      texto: 'É a RKL-2F18, Volvo FH. O frete tava como R$ 4.200 e apareceu R$ 3.800.',
    },
    {
      id: 'm4',
      autor: 'take',
      texto: 'Mariana assumiu o atendimento da IA · 08:05',
    },
    {
      id: 'm5',
      autor: 'out',
      hora: '08:06',
      texto:
        'Oi Rafael, aqui é a Mariana, assumi seu atendimento. Houve um ajuste de pedágio no trecho, mas o valor da carga continua R$ 4.200. Vou corrigir a exibição e te envio o comprovante agora.',
    },
    {
      id: 'm6',
      autor: 'in',
      hora: '08:07',
      texto: 'Beleza! Já mando a foto do CRLV também pra atualizar o cadastro.',
    },
  ],
  documentos: [
    { id: 'd1', nome: 'CNH — frente e verso', meta: 'JPG · enviado 08:05', tipo: 'cnh' },
    { id: 'd2', nome: 'CRLV 2026', meta: 'PDF · enviado 08:07', tipo: 'crlv' },
  ],
  historico: [
    { titulo: 'Frete SP → MG · pagamento', sub: '#FB-04790 · 18/06 · Encerrado', encerrado: true },
    { titulo: 'Atualização de ANTT', sub: '#FB-04612 · 02/06 · Encerrado', encerrado: true },
    { titulo: 'Comprovante de entrega', sub: '#FB-04588 · 21/05 · Encerrado', encerrado: true },
    { titulo: 'Dúvida sobre pedágio na BR-050', sub: '#FB-04471 · 09/05 · Encerrado', encerrado: true },
    { titulo: 'Cadastro de veículo reboque', sub: '#FB-04355 · 27/04 · Encerrado', encerrado: true },
    { titulo: 'Frete MG → SP · avaria na carga', sub: '#FB-04210 · 12/04 · Encerrado', encerrado: true },
    { titulo: 'Atualização de dados bancários', sub: '#FB-04102 · 30/03 · Encerrado', encerrado: true },
  ],
};

// ---- Atendimentos por ticket (cada motorista com sua própria conversa) ----

const ATN_04809: Atendimento = {
  id: 'a-04809',
  protocolo: '#FB-2026-04809',
  assunto: 'Atualização de documentos — CNH vencendo',
  categoria: 'Cadastro / Documentos',
  canal: 'whatsapp',
  responsavel: 'ia',
  sessaoRestante: '22h10',
  sessaoStatus: 'ok',
  prioridade: 'ok',
  motorista: {
    id: 'm-2',
    nome: 'Beatriz Almeida',
    veiculo: 'Scania R450',
    placa: 'BTA-9J04',
    cnh: '0391 8842 220',
    categoria: 'E',
    antt: '87654321',
    validadeCnh: '09/2026',
    cadastrado: false,
    cor: 'rose',
  },
  mensagens: [
    { id: 'b1', autor: 'in', hora: '09:14', texto: 'Oi, recebi um aviso que minha CNH está vencendo. Preciso atualizar aqui na FBLog?' },
    { id: 'b2', autor: 'ia', hora: '09:14', texto: 'Olá, Beatriz! Sua CNH vence em 09/2026. Para seguir aceitando fretes sem bloqueio, envie a nova CNH assim que renovar. Posso te lembrar 30 dias antes?' },
    { id: 'b3', autor: 'in', hora: '09:16', texto: 'Pode sim. Já marquei a renovação pro fim do mês.' },
    { id: 'b4', autor: 'ia', hora: '09:16', texto: 'Perfeito! Deixei um lembrete no seu cadastro. Assim que tiver o documento novo, é só enviar a foto por aqui que eu atualizo.' },
  ],
  documentos: [
    { id: 'bd1', nome: 'CNH atual', meta: 'JPG · vence 09/2026', tipo: 'cnh' },
  ],
  historico: [
    { titulo: 'Cadastro de veículo', sub: '#FB-04471 · 20/05 · Encerrado', encerrado: true },
    { titulo: 'Frete RJ → SP', sub: '#FB-04290 · 28/04 · Encerrado', encerrado: true },
    { titulo: 'Primeiro cadastro na FBLog', sub: '#FB-03980 · 15/02 · Encerrado', encerrado: true },
  ],
};

const ATN_04790: Atendimento = {
  id: 'a-04790',
  protocolo: '#FB-2026-04790',
  assunto: 'Carga não localizada no app de rastreio',
  categoria: 'Rastreio / Operação',
  canal: 'telefone',
  responsavel: 'you',
  sessaoRestante: '02h18',
  sessaoStatus: 'bad',
  prioridade: 'bad',
  motorista: {
    id: 'm-3',
    nome: 'Lucas Ferreira',
    veiculo: 'Mercedes Actros',
    placa: 'LCF-7C55',
    cnh: '0552 1190 447',
    categoria: 'E',
    antt: '44556677',
    validadeCnh: '03/2028',
    cadastrado: true,
    cor: 'amber',
  },
  mensagens: [
    { id: 'l1', autor: 'in', hora: '07:41', texto: 'Bom dia! A carga que peguei em Anápolis não aparece no app de rastreio. Tô parado esperando confirmação.' },
    { id: 'l2', autor: 'ia', hora: '07:41', texto: 'Bom dia, Lucas! Localizei o frete #FB-2026-04790. O status está como "coleta pendente". Vou acionar um atendente para verificar com a operação.' },
    { id: 'l3', autor: 'take', texto: 'Mariana assumiu o atendimento da IA · 07:43' },
    { id: 'l4', autor: 'out', hora: '07:44', texto: 'Oi Lucas, aqui é a Mariana. Já pedi a baixa da coleta pro CD de Anápolis. Em até 10 min o rastreio deve atualizar. Fica na linha que te confirmo.' },
    { id: 'l5', autor: 'in', hora: '07:52', texto: 'Agora apareceu aqui! Já consigo seguir viagem.' },
  ],
  documentos: [
    { id: 'ld1', nome: 'Ordem de coleta', meta: 'PDF · enviado 07:44', tipo: 'outro' },
  ],
  historico: [
    { titulo: 'Carga não localizada', sub: '#FB-04409 · 11/05 · Encerrado', encerrado: true },
    { titulo: 'Pagamento pendente', sub: '#FB-04201 · 22/04 · Encerrado', encerrado: true },
    { titulo: 'Frete GO → DF', sub: '#FB-04050 · 30/03 · Encerrado', encerrado: true },
    { titulo: 'Atualização de dados', sub: '#FB-03870 · 10/02 · Encerrado', encerrado: true },
  ],
};

const ATN_04751: Atendimento = {
  id: 'a-04751',
  protocolo: '#FB-2026-04751',
  assunto: 'Dúvida sobre pagamento do frete de Goiânia',
  categoria: 'Frete / Pagamento',
  canal: 'chat',
  responsavel: 'ia',
  sessaoRestante: '16h02',
  sessaoStatus: 'ok',
  prioridade: 'ok',
  motorista: {
    id: 'm-4',
    nome: 'Patrícia Gomes',
    veiculo: 'DAF XF',
    placa: 'PTG-1A77',
    cnh: '0714 5523 108',
    categoria: 'D',
    antt: '33221100',
    validadeCnh: '11/2027',
    cadastrado: true,
    cor: 'violet',
  },
  mensagens: [
    { id: 'p1', autor: 'in', hora: '10:02', texto: 'Oi! O frete de Goiânia foi entregue ontem mas ainda não caiu o pagamento. Quando recebo?' },
    { id: 'p2', autor: 'ia', hora: '10:02', texto: 'Olá, Patrícia! O pagamento do frete #FB-2026-04751 está programado para D+1 após a confirmação de entrega. A baixa foi registrada às 18h32 de ontem, então o crédito cai hoje até 18h.' },
    { id: 'p3', autor: 'in', hora: '10:03', texto: 'Ah, entendi! E é na mesma conta cadastrada?' },
    { id: 'p4', autor: 'ia', hora: '10:03', texto: 'Sim, na conta terminada em ••4471. Se precisar alterar, consigo abrir a atualização de dados bancários pra você.' },
  ],
  documentos: [
    { id: 'pd1', nome: 'Comprovante de entrega', meta: 'PDF · enviado ontem 18:32', tipo: 'outro' },
  ],
  historico: [
    { titulo: 'Pagamento frete Goiânia', sub: '#FB-04772 · 01/07 · Encerrado', encerrado: true },
    { titulo: 'Frete SP → GO', sub: '#FB-04520 · 15/05 · Encerrado', encerrado: true },
    { titulo: 'Comprovante de entrega', sub: '#FB-04310 · 25/04 · Encerrado', encerrado: true },
  ],
};

const ATN_04738: Atendimento = {
  id: 'a-04738',
  protocolo: '#FB-2026-04738',
  assunto: 'Cadastro de ANTT desatualizado',
  categoria: 'Cadastro / Documentos',
  canal: 'whatsapp',
  responsavel: 'ia',
  sessaoRestante: '09h55',
  sessaoStatus: 'warn',
  prioridade: 'warn',
  motorista: {
    id: 'm-5',
    nome: 'Eduardo Ramos',
    veiculo: 'Iveco Hi-Way',
    placa: 'EDR-4K23',
    cnh: '0668 3391 552',
    categoria: 'E',
    antt: '99887766',
    validadeCnh: '05/2029',
    cadastrado: false,
    cor: 'green',
  },
  mensagens: [
    { id: 'e1', autor: 'in', hora: '08:20', texto: 'Tentei aceitar um frete e deu erro dizendo que meu RNTRC/ANTT está desatualizado.' },
    { id: 'e2', autor: 'ia', hora: '08:20', texto: 'Olá, Eduardo! De fato, seu RNTRC consta como vencido na base da ANTT. Para liberar os fretes, preciso que você envie o comprovante de regularização atualizado.' },
    { id: 'e3', autor: 'in', hora: '08:22', texto: 'Acabei de regularizar no site da ANTT. Mando o print?' },
    { id: 'e4', autor: 'ia', hora: '08:22', texto: 'Pode mandar o print ou o PDF. Assim que eu validar, libero seu cadastro para aceitar fretes de novo.' },
  ],
  documentos: [
    { id: 'ed1', nome: 'RNTRC — comprovante', meta: 'aguardando envio', tipo: 'outro' },
  ],
  historico: [
    { titulo: 'Cadastro de ANTT', sub: '#FB-04751 · 30/06 · Encerrado', encerrado: true },
    { titulo: 'Frete PR → SP', sub: '#FB-04480 · 12/05 · Encerrado', encerrado: true },
    { titulo: 'Primeiro cadastro na FBLog', sub: '#FB-04150 · 20/03 · Encerrado', encerrado: true },
  ],
};

const ATN_NOVO: Atendimento = {
  id: 't-novo',
  protocolo: '#FB-2026-04833',
  assunto: 'Frete de retorno disponível?',
  categoria: 'Frete / Oferta',
  canal: 'whatsapp',
  responsavel: 'you',
  sessaoRestante: '23h58',
  sessaoStatus: 'ok',
  prioridade: 'warn',
  motorista: {
    id: 'm-10',
    nome: 'Sérgio Tavares',
    veiculo: 'Volvo FH 460',
    placa: 'SGT-6P21',
    cnh: '0820 4471 336',
    categoria: 'E',
    antt: '55667788',
    validadeCnh: '07/2028',
    cadastrado: true,
    cor: 'teal',
  },
  mensagens: [
    { id: 's1', autor: 'in', hora: agoraCurto(), texto: 'Boa tarde! Acabei de descarregar em Porto Alegre. Tem algum frete de retorno pra região Sudeste?' },
    { id: 's2', autor: 'ia', hora: agoraCurto(), texto: 'Boa tarde, Sérgio! Deixa eu verificar as ofertas de retorno disponíveis a partir de Porto Alegre. Um instante que já te passo as opções.' },
  ],
  documentos: [],
  historico: [
    { titulo: 'Frete de retorno', sub: '#FB-04612 · 18/06 · Encerrado', encerrado: true },
    { titulo: 'Comprovante de entrega', sub: '#FB-04390 · 02/05 · Encerrado', encerrado: true },
  ],
};

/** Conversa completa por id de ticket. */
export const ATENDIMENTOS: Record<string, Atendimento> = {
  'a-04812': ATENDIMENTO_ATIVO,
  'a-04809': ATN_04809,
  'a-04790': ATN_04790,
  'a-04751': ATN_04751,
  'a-04738': ATN_04738,
  't-novo': ATN_NOVO,
};

export const DASHBOARD: DashboardData = {
  kpis: [
    { k: 'Atendimentos hoje', v: '24', d: '+6 vs. ontem', up: true, ic: 'inbox', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Sessões abertas', v: '5', d: '2 < 6h restantes', up: false, ic: 'clock', cor: 'var(--warn)', fundo: 'var(--warn-sf)' },
    { k: 'Tempo médio de resposta', v: '1m48', d: '-22s vs. meta', up: true, ic: 'bolt', cor: 'var(--ok)', fundo: 'var(--ok-sf)' },
    { k: 'Conversão de fretes', v: '62%', d: '+5 p.p. no mês', up: true, ic: 'route', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Resolvidos pela IA', v: '9', d: 'sem intervenção', up: true, ic: 'ai', cor: 'var(--accent)', fundo: 'var(--accent-sf)' },
    { k: 'Encerrados hoje', v: '17', d: '+3 vs. ontem', up: true, ic: 'check', cor: 'var(--ok)', fundo: 'var(--ok-sf)' },
  ],
  historico: [
    { protocolo: '#FB-04812', nome: 'Rafael Monteiro', cor: 'teal', assunto: 'Divergência no valor da carga', placa: 'RKL-2F18', duracao: 'ativo', duracaoCor: 'var(--ok)', conversao: 'Em frete', conversaoStatus: 'blue' },
    { protocolo: '#FB-04809', nome: 'Beatriz Almeida', cor: 'rose', assunto: 'Atualização de CNH', placa: 'BTA-9J04', duracao: '12m04', duracaoCor: 'var(--ink-2)', conversao: '—', conversaoStatus: 'mut' },
    { protocolo: '#FB-04790', nome: 'Lucas Ferreira', cor: 'amber', assunto: 'Carga não localizada', placa: 'LCF-7C55', duracao: '31m18', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
    { protocolo: '#FB-04772', nome: 'Patrícia Gomes', cor: 'violet', assunto: 'Pagamento frete Goiânia', placa: 'PTG-1A77', duracao: '08m42', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
    { protocolo: '#FB-04751', nome: 'Eduardo Ramos', cor: 'green', assunto: 'Cadastro de ANTT', placa: 'EDR-4K23', duracao: '05m10', duracaoCor: 'var(--ink-2)', conversao: 'Sem frete', conversaoStatus: 'bad' },
    { protocolo: '#FB-04738', nome: 'Antônio Brito', cor: 'slate', assunto: 'Dúvida sobre rota e pedágio', placa: 'ANB-3T90', duracao: '14m55', duracaoCor: 'var(--ink-2)', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  ],
  recebidos: [
    { id: 'r1', nome: 'Sérgio Tavares', cor: 'teal', canal: 'whatsapp', tempo: 'agora', assunto: 'Frete de retorno disponível?', placa: 'SGT-6P21', novo: true },
    { id: 'r2', nome: 'Marina Lopes', cor: 'violet', canal: 'chat', tempo: '1 min', assunto: 'Comprovante de entrega', placa: 'MNL-8R44', novo: true },
  ],
  proximos: [
    { nome: 'Helena Dias', cor: 'amber', canal: 'chat', tempo: '5 min' },
    { nome: 'Antônio Brito', cor: 'slate', canal: 'telefone', tempo: '9 min' },
    { nome: 'Carlos Eduardo', cor: 'green', canal: 'whatsapp', tempo: '12 min' },
  ],
};

// ---- Fila de espera -------------------------------------------------------

export const FILA_ESPERA: FilaEsperaItem[] = [
  {
    id: 'f-1',
    posicao: 1,
    nome: 'Sérgio Tavares',
    cor: 'teal',
    canal: 'whatsapp',
    placa: 'SGT-6P21',
    veiculo: 'Volvo FH 460',
    assunto: 'Frete de retorno disponível?',
    espera: 'agora',
    prioridade: 'warn',
    responsavel: 'ia',
  },
  {
    id: 'f-2',
    posicao: 2,
    nome: 'Marina Lopes',
    cor: 'violet',
    canal: 'chat',
    placa: 'MNL-8R44',
    veiculo: 'Scania R450',
    assunto: 'Comprovante de entrega não chegou',
    espera: '1 min',
    prioridade: 'ok',
    responsavel: 'ia',
  },
  {
    id: 'f-3',
    posicao: 3,
    nome: 'Helena Dias',
    cor: 'amber',
    canal: 'chat',
    placa: 'HLD-2K90',
    veiculo: 'Mercedes Actros',
    assunto: 'Reagendamento de coleta em Campinas',
    espera: '5 min',
    prioridade: 'ok',
    responsavel: 'ia',
  },
  {
    id: 'f-4',
    posicao: 4,
    nome: 'Antônio Brito',
    cor: 'slate',
    canal: 'telefone',
    placa: 'ANB-3T90',
    veiculo: 'DAF XF',
    assunto: 'Dúvida sobre rota e pedágio',
    espera: '9 min',
    prioridade: 'bad',
    responsavel: 'ia',
  },
  {
    id: 'f-5',
    posicao: 5,
    nome: 'Carlos Eduardo',
    cor: 'green',
    canal: 'whatsapp',
    placa: 'CED-7F12',
    veiculo: 'Iveco S-Way',
    assunto: 'Atualização de dados bancários',
    espera: '12 min',
    prioridade: 'warn',
    responsavel: 'ia',
  },
  {
    id: 'f-6',
    posicao: 6,
    nome: 'Roberto Nunes',
    cor: 'blue',
    canal: 'whatsapp',
    placa: 'RBN-1A55',
    veiculo: 'Volvo FH 540',
    assunto: 'Carga com avaria — abrir ocorrência',
    espera: '17 min',
    prioridade: 'bad',
    responsavel: 'ia',
  },
];

// ---- Frota de motoristas --------------------------------------------------

export const MOTORISTAS_FROTA: MotoristaFrota[] = [
  {
    id: 'm-1',
    nome: 'Rafael Monteiro',
    cor: 'teal',
    veiculo: 'Volvo FH 540',
    placa: 'RKL-2F18',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(34) 99812-4471',
    email: 'rafael.monteiro@fblog.com.br',
    cidadeBase: 'Uberlândia, MG',
    localizacao: 'Uberlândia, MG',
    ultimaAtividade: 'há 3 min',
    cadastroCompleto: true,
    fretesMes: 11,
    cnh: '0428 7715 901',
    validadeCnh: '08/2027',
    antt: '12345678',
    desde: 'mar 2021',
    avaliacao: 4.8,
    frete: { origem: 'Uberlândia, MG', destino: 'Campinas, SP', progresso: 62, eta: 'hoje 18h40' },
    fretesHistorico: [
      { id: 'fh-1a', rota: 'Uberlândia → Campinas', data: 'em curso', valor: 'R$ 4.200', status: 'em_curso' },
      { id: 'fh-1b', rota: 'São Paulo → Uberlândia', data: '28 jun', valor: 'R$ 3.850', status: 'entregue' },
      { id: 'fh-1c', rota: 'Ribeirão Preto → São Paulo', data: '21 jun', valor: 'R$ 2.100', status: 'entregue' },
      { id: 'fh-1d', rota: 'Uberaba → Ribeirão Preto', data: '15 jun', valor: 'R$ 1.780', status: 'entregue' },
      { id: 'fh-1e', rota: 'Goiânia → Uberaba', data: '09 jun', valor: 'R$ 2.640', status: 'cancelado' },
    ],
  },
  {
    id: 'm-2',
    nome: 'Beatriz Almeida',
    cor: 'rose',
    veiculo: 'Scania R450',
    placa: 'BTA-9J04',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(11) 99145-2093',
    email: 'beatriz.almeida@fblog.com.br',
    cidadeBase: 'Ribeirão Preto, SP',
    localizacao: 'Ribeirão Preto, SP',
    ultimaAtividade: 'há 12 min',
    cadastroCompleto: false,
    fretesMes: 8,
    cnh: '0512 3390 774',
    validadeCnh: '02/2026',
    antt: '23456781',
    desde: 'jul 2022',
    avaliacao: 4.5,
    fretesHistorico: [
      { id: 'fh-2a', rota: 'Ribeirão Preto → Bauru', data: '30 jun', valor: 'R$ 1.950', status: 'entregue' },
      { id: 'fh-2b', rota: 'Campinas → Ribeirão Preto', data: '24 jun', valor: 'R$ 2.320', status: 'entregue' },
      { id: 'fh-2c', rota: 'São Paulo → Campinas', data: '18 jun', valor: 'R$ 1.480', status: 'entregue' },
    ],
  },
  {
    id: 'm-3',
    nome: 'Lucas Ferreira',
    cor: 'amber',
    veiculo: 'Mercedes Actros',
    placa: 'LCF-7C55',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(62) 99633-7788',
    email: 'lucas.ferreira@fblog.com.br',
    cidadeBase: 'Goiânia, GO',
    localizacao: 'Anápolis, GO',
    ultimaAtividade: 'há 1 min',
    cadastroCompleto: true,
    fretesMes: 14,
    cnh: '0398 5521 640',
    validadeCnh: '11/2028',
    antt: '34567812',
    desde: 'jan 2020',
    avaliacao: 4.9,
    frete: { origem: 'Goiânia, GO', destino: 'Brasília, DF', progresso: 88, eta: 'hoje 15h10' },
    fretesHistorico: [
      { id: 'fh-3a', rota: 'Goiânia → Brasília', data: 'em curso', valor: 'R$ 2.480', status: 'em_curso' },
      { id: 'fh-3b', rota: 'Brasília → Goiânia', data: '29 jun', valor: 'R$ 2.510', status: 'entregue' },
      { id: 'fh-3c', rota: 'Anápolis → Brasília', data: '26 jun', valor: 'R$ 1.640', status: 'entregue' },
      { id: 'fh-3d', rota: 'Goiânia → Anápolis', data: '22 jun', valor: 'R$ 980', status: 'entregue' },
    ],
  },
  {
    id: 'm-4',
    nome: 'Patrícia Gomes',
    cor: 'violet',
    veiculo: 'DAF XF',
    placa: 'PTG-1A77',
    categoria: 'D',
    status: 'disponivel',
    telefone: '(62) 99870-1122',
    email: 'patricia.gomes@fblog.com.br',
    cidadeBase: 'Goiânia, GO',
    localizacao: 'Goiânia, GO',
    ultimaAtividade: 'há 8 min',
    cadastroCompleto: true,
    fretesMes: 6,
    cnh: '0447 8812 335',
    validadeCnh: '05/2027',
    antt: '45678123',
    desde: 'set 2022',
    avaliacao: 4.6,
    fretesHistorico: [
      { id: 'fh-4a', rota: 'Goiânia → Rio Verde', data: '01 jul', valor: 'R$ 2.180', status: 'entregue' },
      { id: 'fh-4b', rota: 'Rio Verde → Goiânia', data: '27 jun', valor: 'R$ 2.050', status: 'entregue' },
    ],
  },
  {
    id: 'm-5',
    nome: 'Eduardo Ramos',
    cor: 'green',
    veiculo: 'Iveco Hi-Way',
    placa: 'EDR-4K23',
    categoria: 'E',
    status: 'descanso',
    telefone: '(41) 99205-6540',
    email: 'eduardo.ramos@fblog.com.br',
    cidadeBase: 'Curitiba, PR',
    localizacao: 'Curitiba, PR',
    ultimaAtividade: 'há 40 min',
    cadastroCompleto: false,
    fretesMes: 9,
    cnh: '0361 4470 228',
    validadeCnh: '09/2025',
    antt: '56781234',
    desde: 'abr 2021',
    avaliacao: 4.3,
    fretesHistorico: [
      { id: 'fh-5a', rota: 'Curitiba → Joinville', data: '30 jun', valor: 'R$ 1.520', status: 'entregue' },
      { id: 'fh-5b', rota: 'Joinville → Curitiba', data: '25 jun', valor: 'R$ 1.480', status: 'entregue' },
      { id: 'fh-5c', rota: 'Ponta Grossa → Curitiba', data: '19 jun', valor: 'R$ 1.130', status: 'entregue' },
    ],
  },
  {
    id: 'm-6',
    nome: 'Antônio Brito',
    cor: 'slate',
    veiculo: 'DAF XF',
    placa: 'ANB-3T90',
    categoria: 'E',
    status: 'em_carga',
    telefone: '(31) 99411-8890',
    email: 'antonio.brito@fblog.com.br',
    cidadeBase: 'Betim, MG',
    localizacao: 'Betim, MG',
    ultimaAtividade: 'há 6 min',
    cadastroCompleto: true,
    fretesMes: 12,
    cnh: '0473 9902 118',
    validadeCnh: '07/2027',
    antt: '67812345',
    desde: 'nov 2019',
    avaliacao: 4.7,
    frete: { origem: 'Belo Horizonte, MG', destino: 'Vitória, ES', progresso: 34, eta: 'amanhã 09h20' },
    fretesHistorico: [
      { id: 'fh-6a', rota: 'Belo Horizonte → Vitória', data: 'em curso', valor: 'R$ 3.640', status: 'em_curso' },
      { id: 'fh-6b', rota: 'Vitória → Belo Horizonte', data: '28 jun', valor: 'R$ 3.480', status: 'entregue' },
      { id: 'fh-6c', rota: 'Betim → Vitória', data: '23 jun', valor: 'R$ 3.510', status: 'entregue' },
    ],
  },
  {
    id: 'm-7',
    nome: 'Carlos Eduardo',
    cor: 'green',
    veiculo: 'Iveco S-Way',
    placa: 'CED-7F12',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(19) 99788-3301',
    email: 'carlos.eduardo@fblog.com.br',
    cidadeBase: 'Campinas, SP',
    localizacao: 'Campinas, SP',
    ultimaAtividade: 'há 15 min',
    cadastroCompleto: true,
    fretesMes: 7,
    cnh: '0405 6673 902',
    validadeCnh: '03/2028',
    antt: '78123456',
    desde: 'fev 2023',
    avaliacao: 4.4,
    fretesHistorico: [
      { id: 'fh-7a', rota: 'Campinas → Sorocaba', data: '01 jul', valor: 'R$ 1.240', status: 'entregue' },
      { id: 'fh-7b', rota: 'Sorocaba → Campinas', data: '26 jun', valor: 'R$ 1.310', status: 'entregue' },
    ],
  },
  {
    id: 'm-8',
    nome: 'Helena Dias',
    cor: 'amber',
    veiculo: 'Mercedes Actros',
    placa: 'HLD-2K90',
    categoria: 'D',
    status: 'manutencao',
    telefone: '(11) 99566-4432',
    email: 'helena.dias@fblog.com.br',
    cidadeBase: 'Jundiaí, SP',
    localizacao: 'Jundiaí, SP',
    ultimaAtividade: 'há 2 h',
    cadastroCompleto: true,
    fretesMes: 5,
    cnh: '0389 1120 447',
    validadeCnh: '12/2026',
    antt: '81234567',
    desde: 'jun 2022',
    avaliacao: 4.6,
    fretesHistorico: [
      { id: 'fh-8a', rota: 'Jundiaí → Campinas', data: '24 jun', valor: 'R$ 980', status: 'entregue' },
      { id: 'fh-8b', rota: 'São Paulo → Jundiaí', data: '20 jun', valor: 'R$ 860', status: 'entregue' },
    ],
  },
  {
    id: 'm-9',
    nome: 'Roberto Nunes',
    cor: 'blue',
    veiculo: 'Volvo FH 540',
    placa: 'RBN-1A55',
    categoria: 'E',
    status: 'offline',
    telefone: '(47) 99320-7765',
    email: 'roberto.nunes@fblog.com.br',
    cidadeBase: 'Joinville, SC',
    localizacao: 'Joinville, SC',
    ultimaAtividade: 'ontem 19h05',
    cadastroCompleto: false,
    fretesMes: 3,
    cnh: '0356 7781 093',
    validadeCnh: '04/2025',
    antt: '19283746',
    desde: 'out 2023',
    avaliacao: 4.1,
    fretesHistorico: [
      { id: 'fh-9a', rota: 'Joinville → Blumenau', data: '18 jun', valor: 'R$ 720', status: 'entregue' },
      { id: 'fh-9b', rota: 'Blumenau → Joinville', data: '12 jun', valor: 'R$ 700', status: 'cancelado' },
    ],
  },
  {
    id: 'm-10',
    nome: 'Sérgio Tavares',
    cor: 'teal',
    veiculo: 'Volvo FH 460',
    placa: 'SGT-6P21',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(51) 99188-2244',
    email: 'sergio.tavares@fblog.com.br',
    cidadeBase: 'Porto Alegre, RS',
    localizacao: 'Porto Alegre, RS',
    ultimaAtividade: 'agora',
    cadastroCompleto: true,
    fretesMes: 10,
    cnh: '0491 2260 815',
    validadeCnh: '10/2027',
    antt: '29384756',
    desde: 'ago 2021',
    avaliacao: 4.8,
    fretesHistorico: [
      { id: 'fh-10a', rota: 'Porto Alegre → Caxias do Sul', data: '30 jun', valor: 'R$ 1.680', status: 'entregue' },
      { id: 'fh-10b', rota: 'Caxias do Sul → Porto Alegre', data: '27 jun', valor: 'R$ 1.640', status: 'entregue' },
      { id: 'fh-10c', rota: 'Pelotas → Porto Alegre', data: '21 jun', valor: 'R$ 2.010', status: 'entregue' },
    ],
  },
  {
    id: 'm-11',
    nome: 'Marina Lopes',
    cor: 'violet',
    veiculo: 'Scania R450',
    placa: 'MNL-8R44',
    categoria: 'D',
    status: 'em_carga',
    telefone: '(21) 99744-9012',
    email: 'marina.lopes@fblog.com.br',
    cidadeBase: 'Duque de Caxias, RJ',
    localizacao: 'Duque de Caxias, RJ',
    ultimaAtividade: 'há 4 min',
    cadastroCompleto: true,
    fretesMes: 13,
    cnh: '0417 8834 550',
    validadeCnh: '06/2028',
    antt: '39485762',
    desde: 'mai 2020',
    avaliacao: 4.9,
    frete: { origem: 'Rio de Janeiro, RJ', destino: 'Juiz de Fora, MG', progresso: 51, eta: 'hoje 20h00' },
    fretesHistorico: [
      { id: 'fh-11a', rota: 'Rio de Janeiro → Juiz de Fora', data: 'em curso', valor: 'R$ 2.780', status: 'em_curso' },
      { id: 'fh-11b', rota: 'Juiz de Fora → Rio de Janeiro', data: '29 jun', valor: 'R$ 2.720', status: 'entregue' },
      { id: 'fh-11c', rota: 'Volta Redonda → Rio de Janeiro', data: '24 jun', valor: 'R$ 1.390', status: 'entregue' },
    ],
  },
  {
    id: 'm-12',
    nome: 'Fernando Dias',
    cor: 'rose',
    veiculo: 'Iveco Hi-Way',
    placa: 'FND-5G30',
    categoria: 'E',
    status: 'disponivel',
    telefone: '(85) 99622-1187',
    email: 'fernando.dias@fblog.com.br',
    cidadeBase: 'Fortaleza, CE',
    localizacao: 'Fortaleza, CE',
    ultimaAtividade: 'há 20 min',
    cadastroCompleto: true,
    fretesMes: 4,
    cnh: '0372 5590 118',
    validadeCnh: '01/2027',
    antt: '48576392',
    desde: 'dez 2022',
    avaliacao: 4.5,
    fretesHistorico: [
      { id: 'fh-12a', rota: 'Fortaleza → Sobral', data: '28 jun', valor: 'R$ 1.870', status: 'entregue' },
      { id: 'fh-12b', rota: 'Sobral → Fortaleza', data: '22 jun', valor: 'R$ 1.820', status: 'entregue' },
    ],
  },
];

// ---- Histórico de atendimentos -------------------------------------------

export const HISTORICO_ATENDIMENTOS: HistoricoAtendimento[] = [
  { id: 'h-1', protocolo: '#FB-04812', motoristaNome: 'Rafael Monteiro', cor: 'teal', placa: 'RKL-2F18', assunto: 'Divergência no valor da carga', canal: 'whatsapp', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-02', dataLabel: '02 jul 2026, 08:12', duracao: '22m10', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-2', protocolo: '#FB-04809', motoristaNome: 'Beatriz Almeida', cor: 'rose', placa: 'BTA-9J04', assunto: 'Atualização de CNH', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-07-02', dataLabel: '02 jul 2026, 07:48', duracao: '12m04', conversao: '—', conversaoStatus: 'mut' },
  { id: 'h-3', protocolo: '#FB-04790', motoristaNome: 'Lucas Ferreira', cor: 'amber', placa: 'LCF-7C55', assunto: 'Carga não localizada', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-01', dataLabel: '01 jul 2026, 16:31', duracao: '31m18', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-4', protocolo: '#FB-04772', motoristaNome: 'Patrícia Gomes', cor: 'violet', placa: 'PTG-1A77', assunto: 'Pagamento frete Goiânia', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-07-01', dataLabel: '01 jul 2026, 14:02', duracao: '08m42', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-5', protocolo: '#FB-04751', motoristaNome: 'Eduardo Ramos', cor: 'green', placa: 'EDR-4K23', assunto: 'Cadastro de ANTT', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-30', dataLabel: '30 jun 2026, 11:20', duracao: '05m10', conversao: 'Sem frete', conversaoStatus: 'bad' },
  { id: 'h-6', protocolo: '#FB-04738', motoristaNome: 'Antônio Brito', cor: 'slate', placa: 'ANB-3T90', assunto: 'Dúvida sobre rota e pedágio', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-30', dataLabel: '30 jun 2026, 09:55', duracao: '14m55', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-7', protocolo: '#FB-04701', motoristaNome: 'Carlos Eduardo', cor: 'green', placa: 'CED-7F12', assunto: 'Atualização de dados bancários', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-27', dataLabel: '27 jun 2026, 15:40', duracao: '06m30', conversao: 'Em frete', conversaoStatus: 'blue' },
  { id: 'h-8', protocolo: '#FB-04688', motoristaNome: 'Helena Dias', cor: 'amber', placa: 'HLD-2K90', assunto: 'Reagendamento de coleta', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-25', dataLabel: '25 jun 2026, 10:12', duracao: '18m47', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-9', protocolo: '#FB-04655', motoristaNome: 'Roberto Nunes', cor: 'blue', placa: 'RBN-1A55', assunto: 'Carga com avaria — ocorrência', canal: 'whatsapp', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-22', dataLabel: '22 jun 2026, 17:05', duracao: '41m02', conversao: '—', conversaoStatus: 'mut' },
  { id: 'h-10', protocolo: '#FB-04612', motoristaNome: 'Sérgio Tavares', cor: 'teal', placa: 'SGT-6P21', assunto: 'Frete de retorno', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-06-18', dataLabel: '18 jun 2026, 08:30', duracao: '09m15', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-11', protocolo: '#FB-04588', motoristaNome: 'Marina Lopes', cor: 'violet', placa: 'MNL-8R44', assunto: 'Comprovante de entrega', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-06-12', dataLabel: '12 jun 2026, 13:22', duracao: '11m48', conversao: 'Em frete', conversaoStatus: 'blue' },
  { id: 'h-12', protocolo: '#FB-04503', motoristaNome: 'Fernando Dias', cor: 'rose', placa: 'FND-5G30', assunto: 'Dúvida sobre nota fiscal', canal: 'telefone', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-05-28', dataLabel: '28 mai 2026, 09:10', duracao: '16m33', conversao: 'Frete fechado', conversaoStatus: 'ok' },
  { id: 'h-13', protocolo: '#FB-04471', motoristaNome: 'Beatriz Almeida', cor: 'rose', placa: 'BTA-9J04', assunto: 'Cadastro de veículo', canal: 'whatsapp', atendente: 'IA', resolvidoPor: 'ia', data: '2026-05-20', dataLabel: '20 mai 2026, 10:44', duracao: '07m19', conversao: 'Sem frete', conversaoStatus: 'bad' },
  { id: 'h-14', protocolo: '#FB-04409', motoristaNome: 'Lucas Ferreira', cor: 'amber', placa: 'LCF-7C55', assunto: 'Pagamento pendente', canal: 'chat', atendente: 'Mariana Costa', resolvidoPor: 'you', data: '2026-05-11', dataLabel: '11 mai 2026, 15:58', duracao: '24m01', conversao: 'Frete fechado', conversaoStatus: 'ok' },
];

// ---- Perfil do atendente --------------------------------------------------

export const PERFIL_ATENDENTE: PerfilAtendente = {
  id: 'u-1',
  nome: 'Mariana Costa',
  email: 'mariana.costa@fblog.com.br',
  telefone: '(11) 99820-3345',
  cor: 'violet',
  funcao: 'atendente',
  metaDiaria: 30,
  disponivel: true,
};
